---
title: "Module Annotation for Pathway enrichment Analysis result"
author:
- name: Xiaotao Shen (https://jaspershen.github.io/)
date: "Created on 2021-12-04 and updated on `r Sys.Date()`"
output:
  html_document:
    df_print: paged
    toc: no
  pdf_document:
    toc: no
vignette: >
  %\VignetteIndexEntry{base_function}
  %\VignettePackage{massdataset}
  % \VignetteEngine{knitr::rmarkdown}
  % \usepackage[utf8]{inputenc}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE, echo=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = TRUE,
  out.width = "100%"
)
```


# Load demo data

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=TRUE}
library(mapa)
if(!require(massdataset)){
  remotes::install_gitlab("tidymass/massdataset")
}
if(!require(org.Hs.eg.db)){
  BiocManager::install("org.Hs.eg.db")
}
data("demo_data", package = "mapa")
load("demo_data.rda")
demo_data
```

# Pathway enrichment
```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=TRUE}
variable_info <-
  demo_data %>%
  massdataset::activate_mass_dataset(what = "variable_info") %>%
  dplyr::filter(fdr < 0.05 & score > 0) %>%
  massdataset::extract_variable_info()

enriched_pathways <-
  enrich_pathway(
    variable_info = variable_info,
    save_to_local = FALSE,
    path = "result",
    OrgDb = org.Hs.eg.db,
    organism = "hsa",
    database = c("go", "reactome", "kegg"),
    ont = "ALL",
    pvalueCutoff = 0.05,
    pAdjustMethod = "BH",
    qvalueCutoff = 0.2,
    minGSSize = 10,
    maxGSSize = 500,
    readable = FALSE,
    pool = FALSE
  )

```

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=TRUE}
enriched_pathways
```

# Merge pathways to get the modules

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=TRUE}
enriched_modules <-
  merge_pathways(
    object = enriched_pathways,
    p.adjust.cutoff.go = 0.05,
    p.adjust.cutoff.kegg = 0.05,
    p.adjust.cutoff.reactome = 0.05,
    count.cutoff.go = 5,
    count.cutoff.kegg = 5,
    count.cutoff.reactome = 5,
    sim.cutoff.go = 0.5,
    sim.cutoff.kegg = 0.5,
    sim.cutoff.reactome = 0.5,
    measure.method.go = "Wang",
    measure.method.kegg = "jaccard",
    measure.method.reactome = "jaccard",
    path = "result",
    save_to_local = FALSE
  )
```

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=TRUE}
enriched_modules
```

# Merge modules to get functional modules

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=TRUE}
enriched_functional_module <-
  merge_modules(
    object = enriched_modules,
    sim.cutoff = 0.5,
    measure_method = c("jaccard"),
    path = "result",
    save_to_local = FALSE
  )
```

# Check the enriched pathways/modules

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=TRUE}
plot_pathway_bar(
  object = enriched_functional_module,
  top_n = 20,
  level = "pathway",
  database = "go"
)

plot_pathway_bar(
  object = enriched_functional_module,
  top_n = 20,
  level = "pathway",
  database = "kegg"
)

plot_pathway_bar(
  object = enriched_functional_module,
  top_n = 20,
  level = "pathway",
  database = "reactome"
)

# plot_pathway_bar(object = enriched_functional_module,
#                  top_n = 20,
#                  level = "module")

plot_pathway_bar(object = enriched_functional_module,
                 top_n = 20,
                 level = "functional_module")


```

# Check the individual module

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=TRUE}
plot <-
  plot_module_info(
    object = enriched_functional_module,
    level = "module",
    database = "go",
    module_id = "go_Module_3"
  )

plot_module_info(
  object = enriched_functional_module,
  level = "module",
  database = "kegg",
  module_id = "kegg_Module_15"
)


enriched_functional_module@merged_module$functional_module_result$module

plot_module_info(object = enriched_functional_module,
                 level = "functional_module",
                 module_id = "Functional_module_17")

# export_module_info_plot(object = object, path = "result2")

```

# The whole similary network

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=TRUE}

plot_similarity_network(
  object = enriched_functional_module,
  level = "module",
  database = "go",
  degree_cutoff = 10
)

plot_similarity_network(
  object = enriched_functional_module,
  level = "module",
  database = "go",
  degree_cutoff = 10,
  module_id = "go_Module_10",
  text_all = TRUE
)

plot_similarity_network(
  object = enriched_functional_module,
  level = "module",
  degree_cutoff = 0,
  database = "go",
  text_all = TRUE
)

plot_similarity_network(
  object = enriched_functional_module,
  level = "module",
  degree_cutoff = 0,
  database = "kegg",
  text_all = TRUE
)

plot_similarity_network(
  object = enriched_functional_module,
  level = "module",
  degree_cutoff = 1,
  database = "reactome",
  text_all = TRUE
)
```

# Relationship network for functional modules/modules/pathways/molecules

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=TRUE}
object <-
  enriched_functional_module
object@merged_module$functional_module_result <-
  head(object@merged_module$functional_module_result, 3)
plot_relationship_network(
  object = object,
  include_functional_modules = TRUE,
  include_modules = FALSE,
  include_pathways = TRUE,
  include_molecules = FALSE,
  functional_module_text = TRUE,
  module_text = TRUE,
  pathway_text = TRUE,
  molecule_text = FALSE,
  circular_plot = FALSE,
  functional_module_arrange_position = TRUE,
  module_arrange_position = TRUE,
  pathway_arrange_position = TRUE,
  molecule_arrange_position = TRUE,
  functional_module_position_limits = c(0, 1),
  module_position_limits = c(0, 1),
  pathway_position_limits = c(0, 1),
  molecule_position_limits = c(0, 1)
)

```

# Export results as excel

```{r,eval=FALSE,warning=FALSE, R.options="", message=FALSE, cache=TRUE}
export_functional_module(object = object)
```


# Session information

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=TRUE}
sessionInfo()
```
