#' Plot Module Information
#'
#' Two object classes are supported:
#' \describe{
#'   \item{\code{functional_module}}{Single-omics enrichment results.
#'     Dispatches to \code{\link{plot_module_info.functional_module}}.}
#'   \item{\code{list}}{Multi-omics integration results (output of
#'     \code{merge_multi_omics_nodes()}).
#'     Dispatches to \code{\link{plot_module_info.list}}.}
#' }
#'
#' @param object The primary object. Either a \code{functional_module} S4 object
#'   (single-omics) or a \code{list} object (multi-omics, produced by
#'   \code{merge_multi_omics_nodes()}).
#' @param ... Additional arguments passed to the corresponding method.
#'   See the method documentation for details.
#'
#' @return See the return value of the dispatched method.
#' @export
plot_module_info <- function(object, ...) {
  UseMethod("plot_module_info")
}


#' @describeIn plot_module_info
#' Method for \code{functional_module} objects.
#' All parameters are identical to the original \code{plot_module_info()} function
#' defined in \file{13_data_visualization_plot_module_info.R}.
#'
#' @param level Character string. Level of biological organisation to visualise:
#'   \code{"module"} or \code{"functional_module"}.
#'   For results generated by \code{get_bioembedsim()} and
#'   \code{merge_pathways_bioembedsim()}, use \code{"functional_module"}.
#' @param database Character string. Source database (only required when
#'   \code{level = "module"}): \code{"go"}, \code{"kegg"}, \code{"reactome"},
#'   \code{"hmdb"}, or \code{"metkegg"}.
#' @param database_color Named character vector of colours for each database.
#' @param module_id A single character string identifying the module to visualise.
#' @param llm_text Logical. Whether to use LLM-generated module names in the
#'   visualisation. Default \code{FALSE}.
#'
#' @return A named list of three \code{ggplot} objects:
#'   \code{network}, \code{barplot}, and \code{wordcloud}.
#' @export
plot_module_info.functional_module <- function(
    object,
    level = c("module", "functional_module"),
    database = c("go", "kegg", "reactome", "hmdb", "metkegg"),
    database_color = c(
      GO = "#eeca40",
      KEGG = "#fd7541",
      Reactome = "#23b9c7",
      HMDB = "#7998ad"
    ),
    module_id,
    llm_text = FALSE,
    ...
) {
  .plot_module_info_functional_module(
    object = object,
    level = level,
    database = database,
    database_color = database_color,
    module_id = module_id,
    llm_text = llm_text,
    ...
  )
}


#' @describeIn plot_module_info
#' Method for \code{list} objects (multi-omics).
#' \code{object} must be the direct output of \code{merge_multi_omics_nodes()},
#' containing elements \code{graph_data}, \code{functional_module_result},
#' and \code{result_with_module}.
#' All other parameters are identical to \code{plot_multi_omics_module_info()}
#' defined in \file{13_data_visualization_plot_multi_omics_module_info.R}.
#'
#' @param node_colors Named character vector of fill colours for each node type
#'   (\code{"gene"}, \code{"metabolite"}, \code{"pathway"}).
#' @param node_shapes Named integer vector of point shapes for each node type.
#' @param edge_colors Named character vector of colours for each edge type.
#' @param node_size Numeric. Base node size. Default \code{5}.
#' @param label_size Numeric. Text label size in pt. Default \code{3}.
#' @param show_rwr_edge Logical. Whether to display diffusion-similarity
#'   (RWR) edges. Default \code{FALSE}.
#' @param show_labels Logical. Whether to display node labels. Default \code{TRUE}.
#' @param title Character string or \code{NULL}. Plot title.
#'   When \code{NULL} (default), \code{module_id} is used as the title.
#'
#' @return A \code{ggplot} / \code{ggraph} object.
#' @export
plot_module_info.list <- function(
    object,
    module_id,
    node_colors = c(
      "gene"       = "#4E79A7",
      "metabolite" = "#F28E2B",
      "pathway"    = "#59A14F"
    ),
    node_shapes = c(
      "gene"       = 21,
      "metabolite" = 24,
      "pathway"    = 22
    ),
    edge_colors = c(
      "TF-target"            = "#E15759",
      "PPI"                  = "#76B7B2",
      "Reaction"             = "#B07AA1",
      "molecule_pathway"     = "#F1CE63",
      "pathway_similarity" = "#439222",
      "diffusion_similarity" = "grey"
    ),
    node_size     = 5,
    label_size    = 3,
    show_rwr_edge = FALSE,
    show_labels   = TRUE,
    title         = NULL,
    ...
) {
  # Forward directly to the original implementation function.
  plot_multi_omics_module_info(
    merge_result  = object,
    module_id     = module_id,
    node_colors   = node_colors,
    node_shapes   = node_shapes,
    edge_colors   = edge_colors,
    node_size     = node_size,
    label_size    = label_size,
    show_rwr_edge = show_rwr_edge,
    show_labels   = show_labels,
    title         = title,
    ...
  )
}


# -----------------------------------------------------------------------------
# Default method: unsupported object classes
# -----------------------------------------------------------------------------

#' @describeIn plot_module_info Default method — raises an informative error for
#'   unsupported object types.
#' @export
plot_module_info.default <- function(object, ...) {
  stop(
    "No 'plot_module_info' method for object of class: ",
    paste(class(object), collapse = ", "), ".\n",
    "Supported classes: 'functional_module', 'list' (multi-omics)."
  )
}
